Add new branch
andreykravchenkoo/Task13A4 pull request #1
Opened 2022-07-28 15:01 UTC by AndreyKravchenkoJava

2022-07-28 21:48 UTC, singeev requested changes

2022-07-28 21:48 UTC, singeev commented on .gitignore
> +*.iml
Круто, что есть `.gitignore`!

Этот файл должен быть в каждом репо.

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/dao/ProjectDAO.java
> +public interface ProjectDAO<K, T> {
В чем назначение этого класса?

Из того, что я вижу дальше - у тебя нет разных имплементаций, т.е. в явном виде интерфейс не нужен.
Методы `close()` - лучше тоже не использовать и закрывать коннекшены по другому - см. коммент в соответствующем классе.

Возможно, ты этот класс сделал просто для тренировки. Тогда вопросов нет. Выглядит хорошо.

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/entity/Letter.java
> +    private String letterSubject;
Обычно стараются давать имен как можно короче, без потери смысла.
Мы находимся в классе `Letter`, у класса есть поле `String subject` - и так понятно, что это будет тема письма. Нет смысла повторять слово `letter` в названии переменных.

Исключение только если у тебя несколько разных `subject` и тебе нужно явно прописать где что.

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/entity/Letter.java
> +    private String departureDate;
`sendDate`

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/entity/Person.java
> +    private String dateBirthday;
`dateOfBirth` или `birthDate`

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/service/PersonDAOImpl.java
> +    private static final String SQL_GET_NOT_BY_SUBJECT_RECIPIENT = "SELECT * FROM person WHERE person.id NOT IN (SELECT DISTINCT person.id FROM Letter JOIN person ON person.id = letter.recipient_id W
Вот этот запрос у меня не работал из-за `Letter` с заглавной буквы. БД ругалась, что нет такой таблицы.
Думаю, это решаемо настройками БД. Но у тебя все остальные таблицы пишутся со строчной буквы - так что лучше исправь, чтобы везде было одинаково.

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/service/LetterDAOImpl.java
> +            preparedStatement = connection.prepareStatement(SQL_ADD_LETTER);
Вот здесь как раз то место, где ты открываешь-закрываешь коннекшены устаревшим способом (и пишешь лишние методы в интерфейсе).

Погугли конструкцию `try-with-resources` - она появилась в более новых версиях языка и позволяет автоматически закрывать ресурсы без использования блока `finally`.

Примерно так:
```
Letter letter = (Letter) entity;
        
        try (Connection connection = ConnectionCreator.createConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(SQL_ADD_LETTER);) {
            

            preparedStatement.setInt(2, letter.getRecipientId());
            preparedStatement.setString(3, letter.getLetterSubject());
            preparedStatement.setString(4, letter.getLetterText());
            preparedStatement.setString(5, letter.getDepartureDate());
            preparedStatement.execute();

            flag = true;

        } catch (SQLException throwables) {
            throwables.printStackTrace();
        } 
        return flag;
```

Т.е. ты объявляешь и инициализируешь ресурсы (переменные) прямо внутри `try` и они будут автоматически закрыты после выполенния кода внутри блока.

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/service/LetterDAOImpl.java
> +            preparedStatement = connection.prepareStatement(SQL_ADD_LETTER);
И еще.

В Java 11+ появилась возможность использовать ключевое слово `var` для переменных, вместо обозначения полного класса, когда класс очевиден.

Например:
```
var connection = ConnectionCreator.createConnection();
```

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/service/LetterDAOImpl.java
> +                letter.setDepartureDate(departureDate);
Создание объекта `letter` из `resultSet` ты делаешь больше одного раза = дублируешь код. Попробуй отрефакторить этот процесс в отдельный метод и переиспользуй.

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/service/LetterDAOImpl.java
> +    public boolean add(Object entity) {
Почему параметр типа `Object`? У тебя DAO класс предназначен для работы с конкретным типом - `Letter`. Все методы должны принимать  параметры типа `Letter`.

И не нужно будет делать каст - `Letter letter = (Letter) entity;`

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/dao/ProjectDAO.java
> +    boolean add(T entity);
Типичное название метода по сохранению объекта в БД - `save`

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/dao/ProjectDAO.java
> +    List<K> getAll();
Типичное название `findAll`

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/service/LetterDAOImpl.java
> +        return flag;
Обычно метод DAO, который сохраняет новый объект в БД возвращает этот самый новый объект с одним изменением - с id, который для него сгенерировала БД при создании новой строки.

Попробуй это реализовать. Если будет сложно - пропусти этот коммент. Сейчас это не так важно.

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/service/LetterDAOImpl.java
> +    public List getAll() {
По хорошему нужно типизировать этот лист - `List<Letter>`

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/service/LetterDAOImpl.java
> +    public Object findById(Object id) {
Метод должен возвращать не `Object`, а `Letter`.

Параметр не `Object id`, а `Integer letterId`.

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/service/LetterDAOImpl.java
> +    public boolean update(Object entity) {
Метод, который делает апдейт объекта в базе обычно возвращает новую версию этого объекта.

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/service/LetterDAOImpl.java
> +    public boolean delete(Object id) {
Обычно метод `delete` ничего не возвращает - `void`. Но если тебе важно получить `boolean` - оставь так.

2022-07-28 21:48 UTC, singeev commented on src/main/java/project/service/LetterDAOImpl.java
> +    private static final String SQL_DELETE_LETTER = "DELETE FROM letter WHERE id = (?)";
Я бы не держал эти SQL-запросы в статик переменных, а поместил их в локальные переменные в каждом методе. Т.е. там где запрос исполняется - там его и пишешь.

2022-07-29 10:41 UTC, AndreyKravchenkoJava commented on src/main/java/project/service/PersonDAOImpl.java
> +    private static final String SQL_GET_NOT_BY_SUBJECT_RECIPIENT = "SELECT * FROM person WHERE person.id NOT IN (SELECT DISTINCT person.id FROM Letter JOIN person ON person.id = letter.recipient_id W
Да, это моя опечатка

2022-07-30 16:21 UTC, singeev commented on src/main/java/project/entity/Person.java
> +    private String dateBirthday;
Смотри, `dateBirthday` дословно переводится - "дата дня рождения". 
На мой взгляд походящие имена для этого поля: "день рождения" - birthday или "дата рождения" - dateOfBirth.

2022-07-31 16:03 UTC, singeev commented on src/main/java/project/dao/LetterDAOImpl.java
> +public class LetterDAOImpl {
Теперь из названия класса можно убрать суффикс "Impl" - уже нет никакого интерфейса.

2022-07-31 16:04 UTC, singeev commented on src/main/java/project/dao/LetterDAOImpl.java
> +    public boolean save(Object entity) {
Вот это еще осталось не исправленным. Передавай сюда параметр типа `Letter`

2022-07-31 16:06 UTC, singeev commented on src/main/java/project/dao/LetterDAOImpl.java
> +        Letter letter = new Letter();
Вот эта переменная вообще не нужна.

2022-07-31 16:08 UTC, singeev commented on src/main/java/project/dao/LetterDAOImpl.java
> +                letterList.add(letter);
Тут, либо используй локальную переменную:
```
                var letter = getLetter(resultSet);
                letterList.add(letter);
```
Либо вызывай метод прямо внутри другого вызова:
```
                letterList.add(getLetter(resultSet));
```

2022-07-31 16:09 UTC, singeev commented on src/main/java/project/dao/LetterDAOImpl.java
> +                letter = getLetter(resultSet);
А что если resultSet будет содержать несколько писем? - судя по твоему коду ты вернешь самое последнее из них. Это то, чего ты ожидаешь?

2022-07-31 16:11 UTC, singeev commented on src/main/java/project/dao/LetterDAOImpl.java
> +        return letter;
Если в базе писем нет, то твой метод все равно вернет объект `Letter`, но со всеми пустыми полями. Так лучше не  делать.
Либо возвращай значение `null` (плохая опция), либо измени этот метод, чтобы он возвращал `Optional<Letter>`.
`Optional` - это новая фича языка начиная с версии Java 8. Если ты еще эту тему не изучал - пока пропусти это. Если изучал - попробуй переделать этот метод (и остальные такие же).

2022-07-31 16:14 UTC, singeev commented on src/main/java/project/dao/PersonDAOImpl.java
> +                personList.add(person);
Если БД вернет 0 персон - ты все равно создаешь пустой объект `Person` и кладешь его в коллекцию. В результате метод вернет лист персон, с размером листа `==1` - это не соответствует реальности.

2022-08-01 14:32 UTC, singeev requested changes

2022-08-01 14:32 UTC, singeev commented on src/main/java/project/dao/LetterDAO.java
> +                optionalLetter = Optional.ofNullable(letter);
`return Optional.ofNullable(letter);`

2022-08-01 14:32 UTC, singeev commented on src/main/java/project/dao/LetterDAO.java
> +        return optionalLetter;
`return Optional.empty();`

2022-08-01 14:32 UTC, singeev commented on src/main/java/project/dao/LetterDAO.java
> +        Optional<Letter> optionalLetter = null;
Эта переменная не нужна.

2022-08-01 14:35 UTC, singeev commented on src/main/java/project/dao/LetterDAO.java
> +        Letter letter = new Letter();
Тут ты снова создаешь объект **еще до того, как даже заглянул в ResultSet**. А если в базе пусто?
Тогда твой метод вернет объект `Letter` с пустыми полями.

2022-09-21 13:12 UTC, merged